### PR TITLE
PE-87 | Added User Info to rating page. Fixed connection with rating service

### PR DESCRIPTION
**Pull request by MaxLian11**
What I Did:
- Connected Rating page with the target user information (user First and Last names, user ID)
- Changed rating page:
  - Rating by default is now 5 stars
  - Minimum rating can be 1 star
  - Skip button is separated from the Done button. If the user clicks Skip, it will close the question, but won't rate the user

How To Test:
- Create a Question. It will have Active status initially
- Ask someone to leave an Answer
- Go to the question details and click the button "Got an answer?" or similar to that
- Choose the best answer
- You must be navigated to the rating page and it must display the target user's first name, last name and profile image
- Test two cases: 
  - Give the user a rating and click done
  - Click skip on the rating page
- Question status "closed" and answer status "bestAnswer" must turn to True
- User's rating must only change if you gave the rating and didn't skip

### CODE REVIEW

**Review by davidsquines — APPROVED** [review]
Works as intended. Good Job

**Review by tonynguyen98 — CHANGES_REQUESTED** [review]
Working as intended, but we shouldn't default  a rating. We should leave it blank and if they click done, and the value is -1, we should have visibility pop up.

**Review by tonynguyen98 — APPROVED** [review]
Looks good, great job!

**Review by dominikyz — APPROVED** [review]
Works as intended! Awesome job!

**Pull request merged**
