### PR TITLE
PE-72| Connect users table with frontend

### PR DESCRIPTION
**Pull request by davidsquines**
What I did:

- Connected Users Table with the frontend portion of the app.

How To Test:
- Checkout into my branch PE-72
- run git fetch and git pull
- Log onto the Firebase Console and delete the email you have been using to test the app.
- Sign up for the application using the same or new email
- Restart the application. 
- If successful, you should be taken to the home page. 
- Go to your IDE console. You should see a couple lines of your first name, last name, and firebase user id. if you can see this
- Confirm that the firebase uid related to your account is the same that is shown in the Firebase Console. If secessful, then the component works

Screen Shot 2021-03-24 at 4 16 29 PM

### CODE REVIEW

**Review by dominikyz — APPROVED** [review]
Works as intended, no issues. Tested with gmail sign up and regular sign up. Great job!

**Review by ayeejane — APPROVED** [review]
Works as intended.

**Comment by ayeejane** [comment]
`Onboarding page` was moved right after `Sign Up page` instead of `Login` though. Don't know if that will create merge conflicts.

**Review by tonynguyen98 — APPROVED** [review]
Looks good, but as Jane said, there have been changes to how the login routing works now. Be aware that I made some changes in my branch since you have merged your branch with this.. Git won't know about these changes since they seem like a regular change, but it will mess up the current logic.

**Pull request merged**
