### PR TITLE
PE-105 | Changed App Icon and Name

### PR DESCRIPTION
**Pull request by ayeejane**
What I Did: 

- Changed the default flutter icon and name to EureQa. 

How to Test: 

- Uninstall and reinstall the app. 
- Run flutter pub get. 
- Once the app is loaded, check to see if the app icon and name have been changed to our logo and name.

### CODE REVIEW

**Review by tonynguyen98 — CHANGES_REQUESTED** [review]
The App Icon is kinda small on my system. Can you make it a bit bigger so its readable: 
unknown
.

**Review by davidsquines — CHANGES_REQUESTED** [review]
Screen Shot 2021-05-02 at 12 39 47 PM
the app icon Is supposed to be white but it is black on iOS emulators

**Review by txt020 — CHANGES_REQUESTED** [review]
The icon on my android emulator looks like this:
image

Can you make the light bulb bigger?

**Review by davidsquines — APPROVED** [review]
It looks better on my iOS emulator
Screen Shot 2021-05-02 at 6 27 04 PM

**Review by txt020 — APPROVED** [review]
image

Much better! Great Job!

**Review by tonynguyen98 — APPROVED** [review]

**Pull request merged**
