### PR TITLE
PE-49 | Implemented RootPage to Handle SharedPreferences()

### PR DESCRIPTION
**Pull request by tonynguyen98**
**What I Did:**
- Created a Root Page to handle any checks for certain status.
- Implemented a Shared Preferences Handler to store all shared preferences app wide.
- Moved any checking functions into Root Page 

**How To Test:**
1. You will need to delete all data for this test!!! You can do this by deleting the app on the device or Android app settings.
2. After running the app, you should see the onboarding. After onboarding, you should see Login(). Don't login yet, instead close the app and reopen to see if the app remembers and goes directly to Login Page.
3. If app remembers, now login.
4. Then close app again and then open. The app should be signed in and you should see the Home Page.
5. Go into General Settings and change the Dark Mode to a different settings. Then go back a screen then open the General Settings again. The settings should be saved. 
6. Sign out. Then close the app and open. The app should be in the Login Page.

### CODE REVIEW

**Review by MaxLian11 — APPROVED** [review]
Everything works perfectly. Code is clean and looks great

**Review by ayeejane — APPROVED** [review]
Everything works as mentioned!

**Review by ayeejane — CHANGES_REQUESTED** [review]
Hitting the back button on the actual phone takes back the user to the Login page instead of exiting out of the app.

**Review by ayeejane — APPROVED** [review]

**Review by davidsquines — APPROVED** [review]
Works as intended

**Pull request merged**
