### PR TITLE
PE-93 | Implemented Gradient Background to SignIn/SignUp

### PR DESCRIPTION
**Pull request by ayeejane**
What I Did: 

- Added gradient background to `Sign In` and `Sign Up` screens. 
- Fixed padding on account email settings. 

How to Test: 

- Sign In and Sign Up as usually and make sure all functionalities are still working.

### CODE REVIEW

**Review by tonynguyen98 — APPROVED** [review]
Looks good! However, the `Sign Up` button kinda blends into the background, is there a way to make it pop a bit?

**Review by txt020 — CHANGES_REQUESTED** [review]
Create account button is off the screen. Can you move the button closer?
image

image

**Review by txt020 — CHANGES_REQUESTED** [review]
Can you move it a little higher? Where the button is not touching the android buttons. 
image

**Review by txt020 — APPROVED** [review]
Okay much better great job!

**Pull request merged**
